//
//  ExportService.swift
//  Auremi
//
//  Created by Krunal Mistry on 11/3/25.
//


import Foundation
import ZIPFoundation

class ExportService {
    static let shared = ExportService()
    
    private init() {}
    
    func exportAllData(completion: @escaping (Result<URL, Error>) -> Void) {
        DispatchQueue.global(qos: .userInitiated).async {
            do {
                // Create temporary directory for export
                let tempDir = FileManager.default.temporaryDirectory
                    .appendingPathComponent("AuremiExport-\(Date().timeIntervalSince1970)")
                
                try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
                
                // Export memories as JSON
                let memories = MemoryManager().getAllMemories()
                let memoriesData = try self.createMemoriesJSON(memories)
                let jsonURL = tempDir.appendingPathComponent("memories.json")
                try memoriesData.write(to: jsonURL)
                
                // Copy photos
                let photosDir = tempDir.appendingPathComponent("photos")
                try FileManager.default.createDirectory(at: photosDir, withIntermediateDirectories: true)
                
                for memory in memories {
                    if let filename = memory.photoFilename,
                       let image = PhotoStorageManager.shared.loadPhoto(filename: filename),
                       let data = image.jpegData(compressionQuality: 0.9) {
                        let photoURL = photosDir.appendingPathComponent(filename)
                        try data.write(to: photoURL)
                    }
                }
                
                // Create README
                let readme = self.createReadme(memoryCount: memories.count)
                let readmeURL = tempDir.appendingPathComponent("README.txt")
                try readme.write(to: readmeURL, atomically: true, encoding: .utf8)
                
                // Create ZIP
                let zipURL = FileManager.default.temporaryDirectory
                    .appendingPathComponent("Auremi-Export-\(Date().timeIntervalSince1970).zip")
                
                try FileManager.default.zipItem(at: tempDir, to: zipURL)
                
                // Clean up temp directory
                try? FileManager.default.removeItem(at: tempDir)
                
                completion(.success(zipURL))
                
            } catch {
                completion(.failure(error))
            }
        }
    }
    
    private func createMemoriesJSON(_ memories: [Memory]) throws -> Data {
        let exportMemories = memories.map { memory -> [String: Any] in
            var dict: [String: Any] = [
                "id": memory.id.uuidString,
                "date": ISO8601DateFormatter().string(from: memory.date),
                "createdAt": ISO8601DateFormatter().string(from: memory.createdAt),
                "modifiedAt": ISO8601DateFormatter().string(from: memory.modifiedAt)
            ]
            
            if let text = memory.text {
                dict["text"] = text
            }
            
            if let filename = memory.photoFilename {
                dict["photoFilename"] = filename
            }
            
            return dict
        }
        
        return try JSONSerialization.data(withJSONObject: exportMemories, options: .prettyPrinted)
    }
    
    private func createReadme(memoryCount: Int) -> String {
        return """
        Auremi Data Export
        =======================
        
        Export Date: \(DateFormatter.shortDate(from: Date()))
        Total Memories: \(memoryCount)
        
        Contents:
        ---------
        • memories.json - All your memories in JSON format
        • photos/ - All your photos
        
        JSON Structure:
        ---------------
        Each memory contains:
        - id: Unique identifier
        - date: Date of the memory
        - text: Your written memory (if any)
        - photoFilename: Associated photo filename (if any)
        - createdAt: When the memory was created
        - modifiedAt: When the memory was last modified
        
        Privacy Note:
        ------------
        This export contains all your personal data from Auremi.
        Keep it secure and delete it when no longer needed.
        
        ---
        Generated by Auremi
        Your memories, your data, your privacy.
        """
    }
}
